pipeline:
  name: ZD-87117
  identifier: ZD87117
  projectIdentifier: BharatLearning
  orgIdentifier: default
  tags: {}
  variables:
    - name: featurebranch
      type: String
      value: <+input>
    - name: IS_CRON_RUN
      type: String
      value: <+input>.default(false)
  stages:
    - stage:
        name: repro
        identifier: repro
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "test"
                          exit 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: Notify_On_Failure_If_Cron
                  identifier: Notify_On_Failure_If_Cron
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Notifying: This scheduled run failed!"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  when:
                    stageStatus: Failure
                    condition: <+pipeline.variables.IS_CRON_RUN> == "true"
